"""Base classes and schemas for Financial Controls.

Every control in ControlChaos inherits from BaseControl and defines:
- key: unique identifier (e.g. gl_subledger_recon)
- name: human readable title
- category: reconciliation, integrity, cutoff, variance, completeness,
            market_data, policy, compliance, risk_scoring, forensic,
            classification, treasury
- description: what the control checks
- intended_error_classes: list of mutation classes this control is designed to detect
- params_model: Pydantic model defining configurable thresholds and rules
- run: execution logic against dataset context or DB session
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, Generic, List, Optional, Type, TypeVar

from pydantic import BaseModel, ConfigDict, Field
from sqlalchemy.orm import Session


@dataclass
class FindingDTO:
    """Standardized finding generated by a control."""

    finding_id: str
    control_id: str
    severity: str  # low, medium, high, critical
    description: str
    affected_row_refs: List[str] = field(default_factory=list)
    amount: Optional[float] = None
    account_code: Optional[str] = None
    period: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "finding_id": self.finding_id,
            "control_id": self.control_id,
            "severity": self.severity,
            "description": self.description,
            "affected_row_refs": self.affected_row_refs,
            "amount": float(self.amount) if self.amount is not None else None,
            "account_code": self.account_code,
            "period": self.period,
            "metadata": self.metadata,
        }


class BaseControlParams(BaseModel):
    """Base parameter model for controls."""

    model_config = ConfigDict(extra="ignore")
    enabled: bool = Field(default=True, description="Whether the control is active in runs")


TParams = TypeVar("TParams", bound=BaseModel)


@dataclass
class DatasetContext:
    """In-memory or DB-backed dataset context for fast execution."""

    dataset_id: str
    gl_entries: List[Any] = field(default_factory=list)
    subledger_entries: List[Any] = field(default_factory=list)
    budget_entries: List[Any] = field(default_factory=list)
    treasury_positions: List[Any] = field(default_factory=list)
    fx_rates: Dict[str, Dict[str, float]] = field(default_factory=dict)  # date -> {pair: rate}
    db_session: Optional[Session] = None


class BaseControl(ABC, Generic[TParams]):
    """Abstract Base Class for all Financial Controls."""

    key: str
    name: str
    category: str
    description: str
    intended_error_classes: List[str]
    params_model: Type[TParams]

    def get_default_params(self) -> Dict[str, Any]:
        """Return default parameters as dictionary."""
        return self.params_model().model_dump()

    def validate_params(self, params: Dict[str, Any]) -> TParams:
        """Validate parameter dictionary against typed model."""
        return self.params_model.model_validate(params)

    @abstractmethod
    def run(self, context: DatasetContext, params: Optional[Dict[str, Any]] = None) -> List[FindingDTO]:
        """Execute the control logic against a dataset context and return findings."""
        pass
