"""Detection Matching Service.

Matches findings generated by controls against ground-truth mutations from mutation_ledger.
Supports strict row overlap, account+period overlap, and partial credit scoring.
"""

from __future__ import annotations

from typing import Dict, List, Set

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.entities import Detection, Finding, MutationLedger


class DetectionMatcher:
    """Matches control findings to ground-truth injected mutations."""

    @classmethod
    def match_run(
        cls,
        db: Session,
        run_id: str,
        dataset_id: str,
        match_mode: str = "strict_row",  # "strict_row" or "account_period"
    ) -> List[Detection]:
        """Perform detection matching between run findings and dataset mutations."""
        # 1. Fetch all ground-truth mutations for the dataset
        mutations = db.execute(
            select(MutationLedger).where(MutationLedger.dataset_id == dataset_id)
        ).scalars().all()

        if not mutations:
            return []

        # 2. Fetch all findings generated in this run
        findings = db.execute(
            select(Finding).where(Finding.run_id == run_id)
        ).scalars().all()

        # Build index of findings by affected row reference
        finding_by_row: Dict[str, List[Finding]] = {}
        for f in findings:
            for ref in f.affected_row_refs:
                if ref not in finding_by_row:
                    finding_by_row[ref] = []
                finding_by_row[ref].append(f)

        detections: List[Detection] = []

        # 3. Match each mutation
        for mut in mutations:
            mut_refs = set(mut.affected_row_refs)
            matching_controls: Set[str] = set()
            is_detected = False
            partial_credit = 0.0

            # Method A: Strict Row Overlap
            for ref in mut_refs:
                matched_findings = finding_by_row.get(ref, [])
                for f in matched_findings:
                    matching_controls.add(f.control_id)
                    is_detected = True
                    partial_credit = 1.0

            # Method B: Account / Period Overlap (Fallback or Relaxed)
            if not is_detected and match_mode == "account_period":
                mut_loc = mut.params.get("location_details", {})
                mut_acc = mut_loc.get("account")
                for f in findings:
                    # If control flagged the same account
                    if mut_acc and mut_acc in f.description:
                        matching_controls.add(f.control_id)
                        is_detected = True
                        partial_credit = 0.5  # Partial credit for account-level catch

            detection = Detection(
                run_id=run_id,
                mutation_id=mut.mutation_id,
                detected=is_detected,
                detected_by=list(matching_controls),
                time_to_detect_ms=10,  # Synthetic time
                partial_credit=partial_credit,
            )
            detections.append(detection)

        # 4. Save detections to DB
        db.bulk_save_objects(detections)
        db.flush()

        return detections
